"""build_docs_pdf.py — Build PDF documentation from HTML sources.

Two PDFs are produced:

  build/docs/presentation.pdf
      Generated from documentation/presentation/index.html.
      Pre-processing step replaces every <iframe src="…"> with an inline
      <div class="print-iframe-inline"> containing the iframe's HTML body,
      so the content is visible to the PDF renderer.

  build/docs/user_documentation.pdf
      Generated by concatenating all chapter pages from
      documentation/user_documentation/ in order (01_…, 02_…, …),
      stripping the nav sidebar from each page and wrapping each chapter
      in a <section class="print-chapter"> for CSS page-break control.

Usage
-----
  python tools/build_docs_pdf.py [--out-dir DIR]

  DIR defaults to  build/docs/

Requirements
------------
  pip install playwright
  playwright install chromium

Rendering is done by Playwright's bundled Chromium using page.pdf(), which
honours @media print CSS rules and produces high-fidelity output.
"""

import argparse
import os
import re
import sys
import tempfile
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _inline_iframes(html: str, base_dir: Path) -> str:
    """Replace every <iframe src="..."> with the body content of that file.

    The replacement is wrapped in a <div class="print-iframe-inline"> so that
    the @media print CSS can style it appropriately.
    """
    def _replace(m: re.Match) -> str:
        tag = m.group(0)
        src_match = re.search(r'src=["\']([^"\']+)["\']', tag, re.IGNORECASE)
        if not src_match:
            return tag
        src = src_match.group(1)
        # Only inline local relative paths — skip data: and http: URIs
        if src.startswith(("http", "data:", "//")):
            return tag
        iframe_path = (base_dir / src).resolve()
        if not iframe_path.is_file():
            return f'<!-- iframe not found: {src} -->'
        iframe_html = _read(iframe_path)
        # Extract everything inside <body>…</body>; fall back to full content
        body_match = re.search(
            r'<body[^>]*>(.*?)</body>', iframe_html,
            re.DOTALL | re.IGNORECASE,
        )
        body_content = body_match.group(1) if body_match else iframe_html
        return (
            f'\n<div class="print-iframe-inline">'
            f'{body_content}'
            f'</div>\n'
        )

    return re.sub(r'<iframe[^>]*>', _replace, html, flags=re.IGNORECASE | re.DOTALL)


def _strip_nav_and_wrap(html: str, chapter_class: str = "print-chapter") -> str:
    """Remove the nav sidebar and wrap the page body in a <section>.

    Strips:
      - the <nav class="nav-sidebar">…</nav> block
      - the outer <html>, <head>, <body> wrapper tags (kept as fragment)

    Returns the inner content wrapped in <section class="print-chapter">.
    """
    # Remove the <nav class="nav-sidebar">…</nav> block (possibly multiline)
    html = re.sub(
        r'<nav\b[^>]*class="[^"]*nav-sidebar[^"]*"[^>]*>.*?</nav>',
        '',
        html,
        flags=re.DOTALL | re.IGNORECASE,
    )
    # Extract body content
    body_match = re.search(
        r'<body[^>]*>(.*?)</body>', html,
        re.DOTALL | re.IGNORECASE,
    )
    content = body_match.group(1) if body_match else html
    return f'<section class="{chapter_class}">\n{content}\n</section>\n'


def _make_base_html(title: str, extra_head: str = "") -> tuple[str, str]:
    """Return (open_tag, close_tag) for a standalone HTML document."""
    head = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
{extra_head}
</head>
<body>
"""
    tail = "\n</body>\n</html>\n"
    return head, tail


# ---------------------------------------------------------------------------
# Shared: Chromium PDF renderer
# ---------------------------------------------------------------------------

def _render_html_to_pdf(html: str, base_dir: Path, out_path: Path) -> None:
    """Render *html* string to PDF at *out_path* using Playwright Chromium.

    A temporary HTML file is written into *base_dir* and loaded via a
    file:// URL so that all relative asset references (fonts, images) in the
    source directory resolve correctly.
    """
    from playwright.sync_api import sync_playwright  # type: ignore

    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Write to a temp file inside base_dir so relative paths resolve
    tmp_fd, tmp_name = tempfile.mkstemp(suffix=".html", dir=base_dir)
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as fh:
            fh.write(html)
        file_url = Path(tmp_name).as_uri()

        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            try:
                page = browser.new_page()
                page.goto(file_url, wait_until="networkidle")
                page.pdf(
                    path=str(out_path),
                    format="A4",
                    print_background=True,
                    margin={"top": "15mm", "bottom": "15mm",
                            "left": "15mm", "right": "15mm"},
                )
            finally:
                browser.close()
    finally:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# Presentation PDF
# ---------------------------------------------------------------------------

def build_presentation_pdf(src_dir: Path, out_path: Path) -> None:
    """Inline iframes then render presentation/index.html → PDF via Chromium."""
    index = src_dir / "index.html"
    print(f"  Reading {index}")
    html = _read(index)

    print(f"  Inlining iframes …")
    html = _inline_iframes(html, base_dir=src_dir)

    print(f"  Rendering → {out_path}")
    _render_html_to_pdf(html, base_dir=src_dir, out_path=out_path)
    print(f"  ✓ {out_path}")


# ---------------------------------------------------------------------------
# User-documentation PDF
# ---------------------------------------------------------------------------

# Ordered list of chapter files. Index is emitted first as the title page,
# then numbered chapters in alphabetical (= numeric) order.
_USER_DOC_CHAPTER_GLOB = "[0-9][0-9]_*.html"


def build_user_docs_pdf(src_dir: Path, out_path: Path) -> None:
    """Concatenate all chapter pages into a single HTML, then render → PDF via Chromium."""
    # Collect chapter files in sorted order
    chapters = sorted(src_dir.glob(_USER_DOC_CHAPTER_GLOB))
    if not chapters:
        print(f"  WARNING: no chapter files found in {src_dir}")

    # The index.html is the title/home page
    index = src_dir / "index.html"
    pages = ([index] if index.is_file() else []) + chapters

    print(f"  Concatenating {len(pages)} pages …")

    # Build a self-contained HTML document:
    #   - inline the shared style.css
    #   - each page becomes a <section class="print-chapter">
    style_css = ""
    css_path = src_dir / "style.css"
    if css_path.is_file():
        style_css = f"<style>\n{_read(css_path)}\n</style>"

    head, tail = _make_base_html(
        title="Project Offline – User Documentation",
        extra_head=style_css,
    )

    sections = []
    for i, page in enumerate(pages):
        print(f"    [{i+1}/{len(pages)}] {page.name}")
        html = _read(page)
        section = _strip_nav_and_wrap(html)
        sections.append(section)

    merged = head + "\n".join(sections) + tail

    print(f"  Rendering → {out_path}")
    # CSS is fully inlined; base_dir covers any remaining font/image refs.
    _render_html_to_pdf(merged, base_dir=src_dir, out_path=out_path)
    print(f"  ✓ {out_path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Build PDF docs from HTML sources.")
    parser.add_argument(
        "--out-dir",
        default=os.path.join("build", "docs"),
        help="Directory where PDFs are written (default: build/docs/)",
    )
    parser.add_argument(
        "--root",
        default=None,
        help="Project root directory (default: parent of this script's directory)",
    )
    args = parser.parse_args()

    root = Path(args.root) if args.root else Path(__file__).resolve().parent.parent
    out_dir = Path(args.out_dir) if os.path.isabs(args.out_dir) else root / args.out_dir

    presentation_src = root / "documentation" / "presentation"
    user_docs_src    = root / "documentation" / "user_documentation"

    print("Building presentation PDF …")
    build_presentation_pdf(presentation_src, out_dir / "presentation.pdf")

    print("Building user documentation PDF …")
    build_user_docs_pdf(user_docs_src, out_dir / "user_documentation.pdf")

    print("\nAll PDFs built successfully.")


if __name__ == "__main__":
    main()
