# import_plantuml.py - Import a PlantUML @startgantt file into an MPXJ ProjectFile
#
# Supported syntax (subset generated by export_gantt.py):
#   Project starts YYYY-MM-DD
#   [Display Name] as [Alias] starts YYYY-MM-DD and lasts N days
#   [Display Name] as [Alias] happens at YYYY-MM-DD          (milestone)
#   [Alias] is N% completed
#   [Alias] is colored in ...                                 (ignored on import)
#   [AliasA] starts after [AliasB]'s end                     (FS dependency)
#   -- comments / blank lines are skipped --

import re

# Compiled patterns
_RE_PROJECT_START = re.compile(
    r"^\s*[Pp]roject\s+starts\s+(\d{4}-\d{2}-\d{2})\s*$"
)
_RE_TASK_DURATION = re.compile(
    r"^\s*\[(.+?)\]\s+as\s+\[(.+?)\]\s+starts\s+(\d{4}-\d{2}-\d{2})\s+and\s+lasts\s+(\d+)\s+days?\s*$"
)
_RE_TASK_MILESTONE = re.compile(
    r"^\s*\[(.+?)\]\s+as\s+\[(.+?)\]\s+happens\s+at\s+(\d{4}-\d{2}-\d{2})\s*$"
)
_RE_PCT_COMPLETE = re.compile(
    r"^\s*\[(.+?)\]\s+is\s+(\d+)%\s+completed\s*$"
)
_RE_COLORED = re.compile(
    r"^\s*\[(.+?)\]\s+is\s+colored\s+in\s+.+$"
)
_RE_DEPENDENCY = re.compile(
    r"^\s*\[(.+?)\]\s+starts\s+after\s+\[(.+?)\]'s\s+end\s*$"
)


def import_plantuml(file_path: str):
    """Parse *file_path* and return an MPXJ ProjectFile.

    Raises an exception if the JVM is not running or if the file cannot be
    parsed.  Returns the populated ProjectFile on success.
    """
    from org.mpxj import ProjectFile, Duration, TimeUnit  # type: ignore
    import jpype  # type: ignore
    import java.time as _jtime  # type: ignore

    # ---- Parse the .puml file ----
    with open(file_path, "r", encoding="utf-8") as fh:
        raw_lines = fh.readlines()

    # Each entry: dict with keys name, alias, start_str, duration_days, is_milestone, pct
    task_entries: list = []
    alias_to_idx: dict = {}    # alias -> index in task_entries
    dependencies: list = []    # (succ_alias, pred_alias)
    project_start_str: str | None = None

    for raw in raw_lines:
        line = raw.strip()
        if not line or line.startswith("'") or line.startswith("@") or line.startswith("printscale"):
            continue

        m = _RE_PROJECT_START.match(line)
        if m:
            project_start_str = m.group(1)
            continue

        m = _RE_TASK_DURATION.match(line)
        if m:
            display, alias, start_str, dur_str = m.group(1), m.group(2), m.group(3), m.group(4)
            idx = len(task_entries)
            task_entries.append({
                "name":         display,
                "alias":        alias,
                "start_str":    start_str,
                "duration_days": int(dur_str),
                "is_milestone": False,
                "pct":          0,
            })
            alias_to_idx[alias] = idx
            continue

        m = _RE_TASK_MILESTONE.match(line)
        if m:
            display, alias, start_str = m.group(1), m.group(2), m.group(3)
            idx = len(task_entries)
            task_entries.append({
                "name":         display,
                "alias":        alias,
                "start_str":    start_str,
                "duration_days": 0,
                "is_milestone": True,
                "pct":          0,
            })
            alias_to_idx[alias] = idx
            continue

        m = _RE_PCT_COMPLETE.match(line)
        if m:
            alias, pct_str = m.group(1), m.group(2)
            if alias in alias_to_idx:
                task_entries[alias_to_idx[alias]]["pct"] = int(pct_str)
            continue

        m = _RE_COLORED.match(line)
        if m:
            continue  # color directives are not imported

        m = _RE_DEPENDENCY.match(line)
        if m:
            succ_alias, pred_alias = m.group(1), m.group(2)
            dependencies.append((succ_alias, pred_alias))
            continue

    if not task_entries:
        raise ValueError("No tasks found in the PlantUML file.")

    # ---- Build the ProjectFile ----
    project = ProjectFile()

    # Set project start date
    if project_start_str:
        y, mo, d = (int(x) for x in project_start_str.split("-"))
        ps_ld = _jtime.LocalDateTime.of(y, mo, d, 8, 0)
        project.getProjectProperties().setStartDate(ps_ld)

    # Map alias → Java task object
    alias_to_task: dict = {}

    for entry in task_entries:
        task = project.addTask()
        task.setName(entry["name"])

        y, mo, d = (int(x) for x in entry["start_str"].split("-"))
        start_ldt = _jtime.LocalDateTime.of(y, mo, d, 8, 0)
        task.setStart(start_ldt)

        if entry["is_milestone"]:
            task.setMilestone(True)
            task.setDuration(Duration.getInstance(0.0, TimeUnit.DAYS))
            task.setFinish(start_ldt)
        else:
            dur_days = float(entry["duration_days"])
            task.setDuration(Duration.getInstance(dur_days, TimeUnit.DAYS))
            finish_ldt = _jtime.LocalDateTime.of(y, mo, d, 8, 0).plusDays(entry["duration_days"])
            task.setFinish(finish_ldt)

        if entry["pct"] > 0:
            Double = jpype.JClass("java.lang.Double")
            task.setPercentageComplete(Double.valueOf(float(entry["pct"])))

        alias_to_task[entry["alias"]] = task

    # ---- Wire up FS dependencies ----
    try:
        _RelBuilder = jpype.JClass("org.mpxj.Relation$Builder")
        zero_lag = Duration.getInstance(0.0, TimeUnit.DAYS)
        from org.mpxj import RelationType  # type: ignore
        fs_type = RelationType.FINISH_START
        for succ_alias, pred_alias in dependencies:
            succ_task = alias_to_task.get(succ_alias)
            pred_task = alias_to_task.get(pred_alias)
            if succ_task is None or pred_task is None:
                continue
            succ_task.addPredecessor(
                _RelBuilder()
                .predecessorTask(pred_task)
                .type(fs_type)
                .lag(zero_lag)
            )
    except Exception as e:
        print(f"[WARN] import_plantuml: could not add dependencies: {e}")

    return project
